### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/global-css-art#18]
- [x] Global CSS
- [x] Home Page
- [x] Search Page
- [x] User Page
- [x] Embed Page
- [x] Art Page

**Comment by sonicx180** [comment]
that's good. pr's are open for dev too right?

**Comment by VulcanWM** [comment]
> that's good. pr's are open for dev too right?

yup! you can contribute to everything on here!

**Comment by sonicx180** [comment]
:+1:
