### ISSUE TITLE
Search bar/page

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/global-css-art#3]
- [x] Search bar at top of home page
- [x] When searching, looks through list of all artwork and sees what matches
- [x] Search bar redirects to /search?s=Search
- [x] Search algorithm: if one word search, display all artids that contain that word
- [x] if multiple words, check if all words are in artid, then append to list
- [x] On search page, search and display results

**Comment by Joseph-Cardona** [comment]
Replit has a tutorial on how to create a search engine https://docs.replit.com/tutorials/nodejs/predictive-text-engine

**Comment by VulcanWM** [comment]
> Replit has a tutorial on how to create a search engine https://docs.replit.com/tutorials/nodejs/predictive-text-engine

i'll check it out thanks!
